{{- if .Values.ingress.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "vote-ui.fullname" . }}
  labels:
    {{- include "vote-ui.labels" . | nindent 4 }}
spec:
  host: "{{ .Values.ingress.host }}"
  to:
    kind: Service
    name: {{ include "vote-ui.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
